# -*- coding: utf-8 -*-
"""loss.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SiS97nSUxeuv9wxNQxQYEAdbcSa4Av2d
"""

def dice_loss(prediction, true, weight):
  overlap=prediction*true
  sum_overlap=torch.sum(overlap,2)
  sum_overlap=torch.sum(sum_overlap,2)
  prediction_shift=prediction-1
  fn=-prediction_shift*true
  fn_sum=torch.sum(fn,2)
  fn_sum=torch.sum(fn_sum,2)
  true_shift=true-1
  fp=-true_shift*prediction
  fp_sum=torch.sum(fp,2)
  fp_sum=torch.sum(fp_sum,2)
  dice=sum_overlap/(sum_overlap+weight*fp_sum+(1-weight)*fn_sum)
  dice=torch.sum(dice)/dice.shape[0]
  return 1-dice